---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/addresses/{id}":
    get:
      summary: Retrieves an address based on the given zipcode
      tags:
      - Addresses
      parameters:
      - name: id
        in: path
        description: zipcode
        required: true
        schema:
          type: string
      - name: access-token
        in: header
        required: true
        description: Access Token
        schema:
          type: string
      - name: client
        in: header
        required: true
        description: Client ID
        schema:
          type: string
      - name: uid
        in: header
        required: true
        description: UID
        schema:
          type: string
      - name: Accept
        in: header
        required: false
        description: Accept
        schema:
          type: string
      responses:
        '200':
          description: address found
          content:
            application/json:
              schema:
                type: object
                properties:
                  zipcode:
                    type: string
                  street:
                    type: string
                  complement:
                    type: string
                  neighborhood:
                    type: string
                  uf:
                    type: string
                  city:
                    type: string
                required:
                - zipcode
                - street
                - neighborhood
                - uf
                - city
        '422':
          description: unprocessable entity
        '401':
          description: unauthorized
  "/api/contacts":
    get:
      summary: Retrieves all contacts user
      tags:
      - Contacts
      parameters:
      - name: page
        in: query
        required: false
        description: Número da página
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Quantidade de registros por página
        schema:
          type: integer
      - name: order
        in: query
        required: false
        description: Campo de ordenação
        schema:
          type: string
      - name: filter_value
        in: query
        required: false
        description: Valor para filtro
        schema:
          type: string
      - name: access-token
        in: header
        required: true
        description: Access Token
        schema:
          type: string
      - name: client
        in: header
        required: true
        description: Client ID
        schema:
          type: string
      - name: uid
        in: header
        required: true
        description: UID
        schema:
          type: string
      - name: Accept
        in: header
        required: false
        description: Accept
        schema:
          type: string
      responses:
        '200':
          description: contacts found
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      "$ref": "#/components/schemas/contact"
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      next_page:
                        type: integer
                        x-nullable: true
                      prev_page:
                        type: integer
                        x-nullable: true
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
    post:
      summary: Creates a contact
      tags:
      - Contacts
      parameters:
      - name: access-token
        in: header
        required: true
        description: Access Token
        schema:
          type: string
      - name: client
        in: header
        required: true
        description: Client ID
        schema:
          type: string
      - name: uid
        in: header
        required: true
        description: UID
        schema:
          type: string
      responses:
        '201':
          description: contact created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/contact"
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                cpf:
                  type: string
                phone:
                  type: string
                address_attributes:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    uf:
                      type: string
                    zipcode:
                      type: string
                    number:
                      type: string
                    complement:
                      type: string
                      x-nullable: true
                    neighborhood:
                      type: string
                  required:
                  - street
                  - city
                  - uf
                  - zipcode
                  - number
                  - neighborhood
              required:
              - name
              - cpf
              - phone
              - address_attributes
  "/api/contacts/{id}":
    get:
      summary: Retrieves a specific contact
      tags:
      - Contacts
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the contact
        schema:
          type: integer
      - name: access-token
        in: header
        required: true
        description: Access Token
        schema:
          type: string
      - name: client
        in: header
        required: true
        description: Client ID
        schema:
          type: string
      - name: uid
        in: header
        required: true
        description: UID
        schema:
          type: string
      - name: Accept
        in: header
        required: false
        description: Accept
        schema:
          type: string
      responses:
        '200':
          description: contact found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/contact"
        '404':
          description: contact not found
    patch:
      summary: Updates a specific contact
      tags:
      - Contacts
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the contact
        schema:
          type: integer
      - name: access-token
        in: header
        required: true
        description: Access Token
        schema:
          type: string
      - name: client
        in: header
        required: true
        description: Client ID
        schema:
          type: string
      - name: uid
        in: header
        required: true
        description: UID
        schema:
          type: string
      responses:
        '200':
          description: contact updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/contact"
        '404':
          description: contact not found
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                cpf:
                  type: string
                phone:
                  type: string
                address_attributes:
                  type: object
                  properties:
                    id:
                      type: integer
                    street:
                      type: string
                    city:
                      type: string
                    uf:
                      type: string
                    zipcode:
                      type: string
                    number:
                      type: string
                    complement:
                      type: string
                      x-nullable: true
                    neighborhood:
                      type: string
    delete:
      summary: Deletes a contact
      tags:
      - Contacts
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the contact
        schema:
          type: integer
      - name: access-token
        in: header
        required: true
        description: Access Token
        schema:
          type: string
      - name: client
        in: header
        required: true
        description: Client ID
        schema:
          type: string
      - name: uid
        in: header
        required: true
        description: UID
        schema:
          type: string
      responses:
        '204':
          description: contact deleted
        '404':
          description: contact not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    contact:
      properties:
        id:
          type: integer
        user_id:
          type: integer
        name:
          type: string
        cpf:
          type: string
        phone:
          type: string
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
        address:
          type: object
          properties:
            id:
              type: integer
            street:
              type: string
            city:
              type: string
            uf:
              type: string
            zipcode:
              type: string
            number:
              type: string
            complement:
              type: string
              x-nullable: true
            neighborhood:
              type: string
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float
        url:
          type: string
      required:
      - id
      - name
      - cpf
      - phone
      - address
